# Generated by Django 5.0.2 on 2024-02-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='est_date',
            new_name='estd',
        ),
    ]
