# Generated by Django 5.0.2 on 2024-02-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='job_title',
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Consultant', 'Consultant'), ('Analyst', 'Analyst'), ('Manager', 'Manager'), ('UI/UX', 'UI/UX'), ('Human Resource', 'Human Resource'), ('Operations', 'Operations')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='upload_resume',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_resumes/'),
        ),
    ]
