# Generated by Django 5.0.2 on 2024-02-20 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_rename_est_date_company_estd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Consultant', 'Consultant'), ('Analyst', 'Analyst'), ('Manager', 'Manager'), ('UI/UX', 'UI/UX'), ('Human Resource', 'Human Resource'), ('Operations', 'Operations')], max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField(default=35000)),
                ('requirements', models.TextField()),
                ('ideal_candidate', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('industry', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Education', 'Education'), ('Transportation', 'Transportation'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Sports', 'Sports'), ('Energy', 'Energy')], max_length=20, null=True)),
                ('state', models.CharField(blank=True, choices=[('Karnataka', 'Karnataka'), ('Assam', 'Assam'), ('Gujarat', 'Gujarat'), ('Kashmir', 'Kashmir'), ('Tamil Nadu', 'Tamil Nadu'), ('Bihar', 'Bihar'), ('Uttar Pradesh', 'Uttar Pradesh')], max_length=20, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Pending', 'Pending')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
            ],
        ),
    ]
